name: shelf_controller_flow_manager
description: A simple application flow management tool in case of an exception or in its normal flow
version: 1.0.1
homepage: https://github.com/RafaelSilvaPereira/shelf_controller_flow_manager

environment:
  sdk: '>=2.12.0 <3.0.0'


dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0
dependencies: 
  shelf: ^1.2.0
